apiVersion: v1
kind: Service
metadata:
  name: broker-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: broker
  ports:
    - port: 80
      targetPort: 8080
      name: http
    - port: 443
      targetPort: 443
      name: https